# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Use triggers to run a pipeline automatically.
# Any changes in master will trigger the job
trigger:
- master

#  An agent is installable software that runs one job at a time.
pool:
  vmImage: 'ubuntu-latest'

# Steps are nothing bt the tasks you want to perform during the build process
# Pipelines > Stages > jobs > Tasks(steps)

jobs:
- job: job1
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  steps:
  - script: echo Job2!
    displayName: 'Run a one-line script'
